# Generated by Django 2.2.5 on 2021-11-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RescueCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address_road', models.CharField(max_length=50)),
                ('address_parcdel', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('opentime', models.CharField(max_length=30)),
                ('closetime', models.CharField(max_length=30)),
                ('dayoff', models.CharField(max_length=30, null=True)),
                ('designated', models.DateField(null=True)),
                ('area', models.IntegerField(null=True)),
                ('num_Vet', models.IntegerField(null=True)),
                ('num_Researcher', models.IntegerField(null=True)),
                ('room_consulation', models.IntegerField(null=True)),
                ('room_operating', models.IntegerField(null=True)),
                ('room_image', models.IntegerField(null=True)),
                ('room_hospital', models.IntegerField(null=True)),
                ('room_genetic', models.IntegerField(null=True)),
                ('room_remedical', models.IntegerField(null=True)),
                ('room_isolated', models.IntegerField(null=True)),
                ('num_vehicle', models.IntegerField(null=True)),
                ('box', models.TextField(null=True)),
                ('equipment_trep', models.TextField(null=True)),
                ('equipment_medical', models.TextField(null=True)),
                ('explain', models.TextField(null=True)),
                ('representative', models.TextField(null=True)),
                ('tel', models.CharField(max_length=30)),
                ('XXX', models.CharField(max_length=30)),
            ],
        ),
    ]
