# Generated by Django 2.2.5 on 2021-11-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuecenter',
            name='area',
            field=models.FloatField(null=True),
        ),
    ]
