# Generated by Django 2.2.5 on 2021-11-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub1app', '0002_auto_20211108_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuecenter',
            name='area',
            field=models.TextField(null=True),
        ),
    ]
