# Generated by Django 2.2.5 on 2021-11-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub1app', '0003_auto_20211108_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuecenter',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rescuecenter',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
