# Generated by Django 2.2.5 on 2021-11-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub1app', '0004_auto_20211108_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_class', models.CharField(max_length=50)),
                ('infoNum', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('natural', models.CharField(max_length=50)),
                ('endangered', models.CharField(max_length=50)),
                ('date_rescue', models.DateField()),
                ('date_result', models.DateField()),
                ('result', models.CharField(max_length=50)),
                ('discoverd_place', models.CharField(max_length=50)),
            ],
        ),
    ]
