# Generated by Django 2.2.5 on 2021-12-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('explain', models.TextField(null=True)),
                ('endangered', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('etc', models.TextField(null=True)),
            ],
        ),
    ]
